services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lumagram-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - lumagram-network
    depends_on:
      - db
    command: >
      sh -c "php artisan migrate --force &&
             php artisan config:cache &&
             php artisan route:cache &&
             php artisan view:cache &&
             php artisan l5-swagger:generate &&
             php-fpm"

  nginx:
    image: nginx:alpine
    container_name: lumagram-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - lumagram-network
    depends_on:
      - app

  db:
    image: postgres:15-alpine
    container_name: lumagram-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - lumagram-network
    ports:
      - "5433:5432"

networks:
  lumagram-network:
    driver: bridge

volumes:
  dbdata: 